version: '1.0'

services:
  redis:
    build: .
    ports:
      - "6379:6379"
    env:
      - REDIS_PASSWORD=sfef*f88wef13HAF&
    command: src/redis-server --requirepass "sfef*f88wef13HAF&" --protected-mode no --bind 0.0.0.0

